services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-container3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD : "true"
      MYSQL_DATABASE: message
    ports:
      - "3308:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    image: message:latest
    container_name: message-container
    depends_on:
      - mysql
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container3:3308/message?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
    networks:
      - mynetwork
networks:
  mynetwork:
    name: hospital_mynetwork
    driver: bridge
volumes:
  mysql_data:
